### ISSUE TITLE
Nothing works without internet

### ISSUE THREAD

**Issue by sky-cake** [reasv/panoptikon#3]
I understand UI updates, and AI model downloads requiring internet on startup and initialization of panoptikon, but offline search of already computed embeddings, even of file paths, appear not to work without internet.

If this can't be remedied, I think a huge disclaimer at the top of the README is necessary.

**Comment by reasv** [comment]
What error are you getting?

**Comment by sky-cake** [comment]
Here are the steps.

1. internet on
2. `python3.12 -m poetry run panoptikon`
3. toggle internet to off
4. search `858` 
5. UI does not update
7. toggle internet to on
8. UI updates with correct results of matching file paths

**Comment by reasv** [comment]
It's because of this https://tanstack.com/query/latest/docs/framework/react/guides/network-mode

**Comment by reasv** [comment]
This should be fixed in the latest master

**Comment by sky-cake** [comment]
I don't see a config for `.*network.*` anywhere in the project. Is it possible to change networkMode to `offlineFirst` as a user?

**Comment by sky-cake** [comment]
Thank you !

**Comment by sky-cake** [comment]
Confirmed to be working, cheers dude
